name: Sync develop with main after release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'chore(main): release')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Merge main into develop
        run: |
          git fetch origin main
          git merge origin/main
          git push origin develop